# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ip_design/ip_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design || ORIG_REF_NAME==ip_design} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_processing_system7_0_0/ip_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_processing_system7_0_0 || ORIG_REF_NAME==ip_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_ps7_0_axi_periph_0/ip_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==ip_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_rst_ps7_0_100M_0/ip_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==ip_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_xbar_0/ip_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_xbar_0 || ORIG_REF_NAME==ip_design_xbar_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_matrix_mult_0_1/ip_design_matrix_mult_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_matrix_mult_0_1 || ORIG_REF_NAME==ip_design_matrix_mult_0_1} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_axi_intc_0_0/ip_design_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_axi_intc_0_0 || ORIG_REF_NAME==ip_design_axi_intc_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_auto_pc_0/ip_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_design_auto_pc_0 || ORIG_REF_NAME==ip_design_auto_pc_0} -quiet] -quiet

# XDC: bd/ip_design/ip_design_ooc.xdc
