# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fabian/Documents/ensta/deuxieme/sys_elec_embar/Zynq_Book/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_matrix_mult_0_1/ip_design_matrix_mult_0_1.xci
# IP: The module: 'ip_design_matrix_mult_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fabian/Documents/ensta/deuxieme/sys_elec_embar/Zynq_Book/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_matrix_mult_0_1/constraints/matrix_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_design_matrix_mult_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/fabian/Documents/ensta/deuxieme/sys_elec_embar/Zynq_Book/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_matrix_mult_0_1/ip_design_matrix_mult_0_1.xci
# IP: The module: 'ip_design_matrix_mult_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fabian/Documents/ensta/deuxieme/sys_elec_embar/Zynq_Book/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_matrix_mult_0_1/constraints/matrix_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_design_matrix_mult_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
