# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fabian/Documents/ensta/deuxieme/sys_elec_embar/Zynq_Book/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_axi_intc_0_0/ip_design_axi_intc_0_0.xci
# IP: The module: 'ip_design_axi_intc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fabian/Documents/ensta/deuxieme/sys_elec_embar/Zynq_Book/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_axi_intc_0_0/ip_design_axi_intc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_design_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/fabian/Documents/ensta/deuxieme/sys_elec_embar/Zynq_Book/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_axi_intc_0_0/ip_design_axi_intc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_design_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/fabian/Documents/ensta/deuxieme/sys_elec_embar/Zynq_Book/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_axi_intc_0_0/ip_design_axi_intc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_design_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/fabian/Documents/ensta/deuxieme/sys_elec_embar/Zynq_Book/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_axi_intc_0_0/ip_design_axi_intc_0_0.xci
# IP: The module: 'ip_design_axi_intc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fabian/Documents/ensta/deuxieme/sys_elec_embar/Zynq_Book/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_axi_intc_0_0/ip_design_axi_intc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_design_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/fabian/Documents/ensta/deuxieme/sys_elec_embar/Zynq_Book/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_axi_intc_0_0/ip_design_axi_intc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_design_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/fabian/Documents/ensta/deuxieme/sys_elec_embar/Zynq_Book/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_axi_intc_0_0/ip_design_axi_intc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_design_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
