// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x40 ~
// 0x7f : Memory 'a' (5 * 40b)
//        Word 2n   : bit [31:0] - a[n][31: 0]
//        Word 2n+1 : bit [ 7:0] - a[n][39:32]
//                    others     - reserved
// 0x80 ~
// 0xbf : Memory 'b' (5 * 40b)
//        Word 2n   : bit [31:0] - b[n][31: 0]
//        Word 2n+1 : bit [ 7:0] - b[n][39:32]
//                    others     - reserved
// 0xc0 ~
// 0xff : Memory 'prod' (25 * 16b)
//        Word n : bit [15: 0] - prod[2n]
//                 bit [31:16] - prod[2n+1]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XMATRIX_MULT_AXILITES_ADDR_A_BASE    0x40
#define XMATRIX_MULT_AXILITES_ADDR_A_HIGH    0x7f
#define XMATRIX_MULT_AXILITES_WIDTH_A        40
#define XMATRIX_MULT_AXILITES_DEPTH_A        5
#define XMATRIX_MULT_AXILITES_ADDR_B_BASE    0x80
#define XMATRIX_MULT_AXILITES_ADDR_B_HIGH    0xbf
#define XMATRIX_MULT_AXILITES_WIDTH_B        40
#define XMATRIX_MULT_AXILITES_DEPTH_B        5
#define XMATRIX_MULT_AXILITES_ADDR_PROD_BASE 0xc0
#define XMATRIX_MULT_AXILITES_ADDR_PROD_HIGH 0xff
#define XMATRIX_MULT_AXILITES_WIDTH_PROD     16
#define XMATRIX_MULT_AXILITES_DEPTH_PROD     25

